on:
  push:
    tags:
      - 'v*'

name: Create Release

env:
  version: ${{ github.ref }}

jobs:
  auto-create-release:
    name: Auto Create Release
    runs-on: windows-latest
    steps:
      - name: Build with Maven
        run: |
          echo ${{ env.version }}
      - name: Get version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}